name: Test Kotlin Build & Runner

# This workflow can only be triggered manually from the GitHub Actions UI.
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running this test workflow'
        required: false
        default: 'Manual test of runner connectivity.'

jobs:
  test_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Run Full Gradle Build
        run: |
          echo "Running build to verify Kotlin compilation and task execution..."
          ./gradlew build

      - name: Success Message
        run: echo "✅ Kotlin project built successfully on the runner."